export const ADD_DATA = "ADD_DATA";
export const ADD_ADMIN_REQUEST = 'ADD_ADMIN_REQUEST';
export const ADD_ADMIN_REJECT = 'ADD_ADMIN_REJECT';

// get 
export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const FAILURE_DATA = 'FAILURE_DATA';

export const SINGLE_ADMIN_REQUEST = "SINGLE_ADMIN_REQUEST";
export const SINGLE_ADMIN_RECEIVE = "SINGLE_ADMIN_RECEIVE";
export const SINGLE_ADMIN_REJECT = "SINGLE_ADMIN_FAILURE";


